version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
      - "5558:5555"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5438/showcase-pro
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=showcase-pro
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5438:5432"
volumes:
  pgdata: